name: iOS Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Manual trigger

jobs:
  build-ios:
    name: Build iOS App
    runs-on: macos-15 # Xcode 16.x, iOS SDK 18.x - App Store ready until April 2026

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.27.x' # Latest stable

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Setup Firebase Config (iOS)
        run: |
          # Create GoogleService-Info.plist from secret
          # For now, use a placeholder to allow build without real Firebase config
          echo "⚠️ Using placeholder Firebase config - notifications will not work"
          cat > ios/Runner/GoogleService-Info.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>API_KEY</key>
            <string>PLACEHOLDER_API_KEY</string>
            <key>GCM_SENDER_ID</key>
            <string>000000000000</string>
            <key>PLIST_VERSION</key>
            <string>1</string>
            <key>BUNDLE_ID</key>
            <string>com.spotwatt.app</string>
            <key>PROJECT_ID</key>
            <string>spotwatt-900e9</string>
            <key>STORAGE_BUCKET</key>
            <string>spotwatt-900e9.firebasestorage.app</string>
            <key>IS_ADS_ENABLED</key>
            <false/>
            <key>IS_ANALYTICS_ENABLED</key>
            <false/>
            <key>IS_APPINVITE_ENABLED</key>
            <false/>
            <key>IS_GCM_ENABLED</key>
            <true/>
            <key>IS_SIGNIN_ENABLED</key>
            <true/>
            <key>GOOGLE_APP_ID</key>
            <string>1:000000000000:ios:0000000000000000000000</string>
          </dict>
          </plist>
          EOF

      - name: Analyze code
        run: flutter analyze
        continue-on-error: true # Don't fail build on analysis warnings

      - name: Run tests
        run: flutter test
        continue-on-error: true # Don't fail if no tests exist

      - name: Build iOS (Debug, no codesign)
        run: |
          flutter build ios --debug --no-codesign

      # Optional: Build Release IPA (requires code signing setup)
      # - name: Build iOS Release IPA
      #   run: |
      #     flutter build ipa --release
      #   env:
      #     # Add your code signing secrets here:
      #     # APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
      #     # APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}

      - name: Upload iOS build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: |
            build/ios/iphoneos/Runner.app
          retention-days: 7
