name: iOS Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Manual trigger

jobs:
  build-ios:
    name: Build iOS App
    runs-on: macos-13 # Xcode 14.3.1, iOS SDK 16.4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.27.x' # Latest stable

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze
        continue-on-error: true # Don't fail build on analysis warnings

      - name: Run tests
        run: flutter test
        continue-on-error: true # Don't fail if no tests exist

      - name: Build iOS (Debug, no codesign)
        run: |
          flutter build ios --debug --no-codesign

      # Optional: Build Release IPA (requires code signing setup)
      # - name: Build iOS Release IPA
      #   run: |
      #     flutter build ipa --release
      #   env:
      #     # Add your code signing secrets here:
      #     # APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
      #     # APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}

      - name: Upload iOS build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: |
            build/ios/iphoneos/Runner.app
          retention-days: 7
